### ISSUE TITLE
dep init problem

### ISSUE THREAD

**Issue by doctornkz** [signalfx/golib#169] opened 2020-01-17 11:42 UTC
Hello!
I can't use `dep` tool anymore with my project (here: https://github.com/olx-global/signalfx2terraform) , because I am receiving a lot of errors about signalfx/golib:
```Solving failure: No versions of github.com/signalfx/golib met constraints:
        v3.1.0: Could not introduce github.com/signalfx/golib@v3.1.0, as its subpackage github.com/signalfx/golib/v3/pointer is missing. (Package is required by github.com/s
ignalfx/signalfx-go@v1.6.11.)
        v3.0.0: Could not introduce github.com/signalfx/golib@v3.0.0, as its subpackage github.com/signalfx/golib/v3/pointer is missing. (Package is required by github.com/s
ignalfx/signalfx-go@v1.6.11.)
```
and so one. 
I am using 
```
dep version
dep:
 version     : v0.5.4
 build date  : 
 git hash    : 
 go version  : go1.12.6
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false
```

What did happen with golib?

**Comment by jgheewala** [comment] 2020-01-17 16:59
@doctornkz golib has been migrated to go mod. You can find more details https://github.com/signalfx/golib/releases/tag/v3.0.0

**Comment by jgheewala** [comment] 2020-05-20 23:20
closing this. feel free to reopen if the issue is still seen

**Closed by jgheewala** 2020-05-20 23:20 UTC
